let lastAnalysis = null;
const analyzeBtn = document.getElementById('analyze-btn'); const analyzeStatus = document.getElementById('analyze-status'); const resultArea = document.getElementById('result-area');
function updateGraphButton() { const count = getNotes().length; analyzeBtn.disabled = count < 2; document.getElementById('analyze-hint').hidden = count >= 2; }
function demoData(large = false) {
  if (!large) return { notes: [{ id: 'demo-1', title: '아침 루틴 개선', content: '출근 전 20분 동안 오늘의 우선순위와 할 일을 정리하는 습관을 만들고 싶다.' }, { id: 'demo-2', title: '집중 시간을 늘리는 방법', content: '25분 집중과 5분 휴식을 반복하고 알림을 끄면 중요한 작업에 더 오래 몰입할 수 있다.' }, { id: 'demo-3', title: '주간 회고 노트', content: '매주 금요일에 잘한 일과 아쉬운 일을 기록하고 다음 주에 바꿀 한 가지를 정한다.' }, { id: 'demo-4', title: '독서 메모 습관', content: '책에서 기억할 문장과 떠오른 생각을 짧은 노트로 남겨 다른 아이디어와 연결한다.' }, { id: 'demo-5', title: '나만의 지식 관리', content: '작은 메모를 태그와 내부링크로 이어서 나중에 다시 찾을 수 있는 지식 지도를 만든다.' }], links: [{ from: 'demo-1', to: 'demo-2', reason: '루틴과 집중을 함께 개선할 수 있어요.' }, { from: 'demo-1', to: 'demo-3', reason: '실천 결과를 회고로 점검해요.' }, { from: 'demo-2', to: 'demo-4', reason: '집중 시간은 독서 습관의 기반이에요.' }, { from: 'demo-4', to: 'demo-5', reason: '메모 연결이 지식 관리로 이어져요.' }], tags: {} };
  const topics = ['생산성', '독서', '운동', '여행', '요리', '외국어', '재테크', '커리어', '창작', '관계']; const notes = []; const links = [];
  topics.forEach((topic, group) => { let previous; for (let i = 1; i <= 10; i += 1) { const id = `large-${group}-${i}`; notes.push({ id, title: `${topic} · 메모 ${i}`, content: `${topic}에 관한 ${i}번째 생각입니다. 떠오른 아이디어와 다음 행동을 기록합니다.` }); if (previous) links.push({ from: previous, to: id, reason: `${topic} 안에서 이어지는 생각이에요.` }); previous = id; } if (group) links.push({ from: `large-${group - 1}-1`, to: `large-${group}-1`, reason: '서로 다른 주제의 확장 아이디어예요.' }); });
  return { notes, links, tags: {} };
}
function renderResult(data) { lastAnalysis = data; resultArea.hidden = false; renderGraph(data.notes, data.links); }
analyzeBtn.addEventListener('click', async () => { const notes = getNotes(); analyzeBtn.disabled = true; showLoading(analyzeStatus, true); try { const data = await callApi('/api/connect', { notes: notes.map(({ id, title, content }) => ({ id, title, content })), ai: getAiSettings() }); showLoading(analyzeStatus, false); renderResult({ notes, links: data.links, tags: data.tags || {} }); recordAiUse(); } catch (err) { showError(analyzeStatus, errorMessage(err)); } finally { updateGraphButton(); } });
document.getElementById('demo-graph-btn').addEventListener('click', () => { analyzeStatus.innerHTML = '<p class="muted">예시 데이터입니다. 노드를 끌거나 클릭해보세요.</p>'; renderResult(demoData()); });
document.getElementById('demo-large-graph-btn').addEventListener('click', () => { analyzeStatus.innerHTML = '<p class="muted">10개 주제, 100개 예시 메모를 자유 배치로 표시했어요.</p>'; renderResult(demoData(true)); });
document.getElementById('copy-md-btn').addEventListener('click', (event) => { if (!lastAnalysis) return; copyText(lastAnalysis.notes.map((note) => `## ${note.title}\n\n${note.content}`).join('\n---\n\n'), event.target); });
updateGraphButton();
